// resources/js/components/Dashboard/CalendarScheduleWidget.vue
<script setup lang="ts">
interface CalendarEventItem {
    id: number;
    title: string;
    start_at: string;
    end_at: string | null;
    is_all_day: boolean;
    color: string | null;
    location: string | null;
}

defineProps<{
    events: CalendarEventItem[];
}>();

function formatDate(value: string) {
    return new Date(value).toLocaleDateString(undefined, { weekday: 'short', month: 'short', day: 'numeric' });
}

function formatTime(value: string) {
    return new Date(value).toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' });
}
</script>

<template>
    <div class="flex flex-col gap-2">
        <div v-if="events.length === 0" class="py-8 text-center text-sm text-muted-foreground">No upcoming events in the next 14 days.</div>
        <ul v-else class="space-y-2">
            <li v-for="event in events" :key="event.id" class="flex items-start gap-3 rounded-lg border p-3">
                <div class="mt-0.5 size-2.5 shrink-0 rounded-full" :style="{ backgroundColor: event.color ?? '#6366f1' }" />
                <div class="min-w-0 flex-1">
                    <p class="truncate text-sm font-medium">{{ event.title }}</p>
                    <p class="text-xs text-muted-foreground">
                        {{ formatDate(event.start_at) }}
                        <template v-if="!event.is_all_day"> · {{ formatTime(event.start_at) }}</template>
                        <template v-if="event.location"> · {{ event.location }}</template>
                    </p>
                </div>
            </li>
        </ul>
    </div>
</template>

// resources/js/components/Dashboard/CalendarScheduleWidget.tsx
interface CalendarEventItem {
    id: number;
    title: string;
    start_at: string;
    end_at: string | null;
    is_all_day: boolean;
    color: string | null;
    location: string | null;
}

interface CalendarScheduleWidgetProps {
    events: CalendarEventItem[];
}

function formatDate(value: string): string {
    return new Date(value).toLocaleDateString(undefined, { weekday: 'short', month: 'short', day: 'numeric' });
}

function formatTime(value: string): string {
    return new Date(value).toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' });
}

export default function CalendarScheduleWidget({ events }: CalendarScheduleWidgetProps) {
    return (
        <div className="flex flex-col gap-2">
            {events.length === 0 ? (
                <div className="py-8 text-center text-sm text-muted-foreground">No upcoming events in the next 14 days.</div>
            ) : (
                <ul className="space-y-2">
                    {events.map((event) => (
                        <li key={event.id} className="flex items-start gap-3 rounded-lg border p-3">
                            <div className="mt-0.5 size-2.5 shrink-0 rounded-full" style={{ backgroundColor: event.color ?? '#6366f1' }} />
                            <div className="min-w-0 flex-1">
                                <p className="truncate text-sm font-medium">{event.title}</p>
                                <p className="text-xs text-muted-foreground">
                                    {formatDate(event.start_at)}
                                    {!event.is_all_day && ` · ${formatTime(event.start_at)}`}
                                    {event.location && ` · ${event.location}`}
                                </p>
                            </div>
                        </li>
                    ))}
                </ul>
            )}
        </div>
    );
}
