// resources/js/pages/Family/Join.tsx
import { Head, useForm } from '@inertiajs/react';
import { joinStore } from '@/actions/App/Http/Controllers/FamilyController';
import InputError from '@/components/InputError';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import AppLayout from '@/layouts/AppLayout';
import type { BreadcrumbItem } from '@/types';

const breadcrumbs: BreadcrumbItem[] = [{ title: 'Join Family', href: '/family/join' }];

export default function FamilyJoin() {
    const { data, setData, post, processing, errors } = useForm({ invite_code: '' });

    function handleSubmit(e: React.FormEvent) {
        e.preventDefault();
        post(joinStore().url);
    }

    return (
        <>
            <Head title="Join Family" />
            <AppLayout breadcrumbs={breadcrumbs}>
                <div className="flex items-center justify-center p-8">
                    <div className="w-full max-w-md space-y-6">
                        <div>
                            <h1 className="text-2xl font-bold">Join a Family</h1>
                            <p className="mt-1 text-sm text-muted-foreground">Enter the invite code shared by your family admin.</p>
                        </div>
                        <form onSubmit={handleSubmit} className="space-y-4">
                            <div className="grid gap-2">
                                <Label htmlFor="invite_code">Invite Code</Label>
                                <Input
                                    id="invite_code"
                                    value={data.invite_code}
                                    onChange={(e) => setData('invite_code', e.target.value.toUpperCase())}
                                    placeholder="e.g. ABCD1234"
                                    required
                                    className="uppercase"
                                />
                                <InputError message={errors.invite_code} />
                            </div>
                            <Button type="submit" className="w-full" disabled={processing}>
                                {processing ? 'Joining…' : 'Join Family'}
                            </Button>
                        </form>
                    </div>
                </div>
            </AppLayout>
        </>
    );
}

// resources/js/pages/Family/Join.vue
<script setup lang="ts">
import { joinStore } from '@/actions/App/Http/Controllers/FamilyController';
import InputError from '@/components/InputError.vue';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import AppLayout from '@/layouts/AppLayout.vue';
import { type BreadcrumbItem } from '@/types';
import { Form, Head } from '@inertiajs/vue3';

const breadcrumbs: BreadcrumbItem[] = [{ title: 'Join Family', href: '/family/join' }];
</script>

<template>
    <Head title="Join Family" />

    <AppLayout :breadcrumbs="breadcrumbs">
        <div class="flex items-center justify-center p-8">
            <div class="w-full max-w-md space-y-6">
                <div>
                    <h1 class="text-2xl font-bold">Join a Family</h1>
                    <p class="mt-1 text-sm text-muted-foreground">Enter the invite code shared by your family admin.</p>
                </div>

                <Form :action="joinStore()" method="post" class="space-y-4" v-slot="{ errors, processing }">
                    <div class="grid gap-2">
                        <Label for="invite_code">Invite Code</Label>
                        <Input id="invite_code" name="invite_code" placeholder="e.g. ABCD1234" required class="uppercase" />
                        <InputError :message="errors.invite_code" />
                    </div>

                    <Button type="submit" class="w-full" :disabled="processing">
                        {{ processing ? 'Joining…' : 'Join Family' }}
                    </Button>
                </Form>
            </div>
        </div>
    </AppLayout>
</template>
