// resources/js/components/ui/datetime-input/DateTimeInput.vue
<script setup lang="ts">
import { cn } from '@/lib/utils';
import { useVModel } from '@vueuse/core';
import type { HTMLAttributes } from 'vue';

const props = defineProps<{
    defaultValue?: string;
    modelValue?: string;
    class?: HTMLAttributes['class'];
    name?: string;
    required?: boolean;
    disabled?: boolean;
    placeholder?: string;
}>();

const emits = defineEmits<{
    (e: 'update:modelValue', payload: string): void;
}>();

const modelValue = useVModel(props, 'modelValue', emits, {
    passive: true,
    defaultValue: props.defaultValue,
});
</script>

<template>
    <input
        v-model="modelValue"
        type="datetime-local"
        :name="name"
        :required="required"
        :disabled="disabled"
        data-slot="input"
        :class="
            cn(
                'border-input dark:bg-input/30 flex h-9 w-full min-w-0 rounded-md border bg-transparent px-3 py-1 text-sm shadow-xs transition-[color,box-shadow] outline-none',
                'focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px]',
                'disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50',
                '[color-scheme:light] dark:[color-scheme:dark]',
                props.class,
            )
        "
    />
</template>

// resources/js/components/ui/datetime-input/index.tsx
import * as React from 'react';
import { cn } from '@/lib/utils';

function DateTimeInput({ className, ...props }: React.ComponentProps<'input'>) {
    return (
        <input
            type="datetime-local"
            data-slot="datetime-input"
            className={cn(
                // Mimics MT's outlined input appearance without using Input
                // (MT's Input coerces unsupported types like datetime-local back to text)
                'w-full select-none rounded-md border border-surface bg-transparent px-2.5 py-2 text-sm text-black shadow-sm ring ring-transparent outline-none transition-all duration-300 ease-in [color-scheme:light] hover:border-primary hover:ring-primary/10 focus:border-primary focus:ring-primary/10 focus:outline-none disabled:pointer-events-none disabled:opacity-50 dark:text-white dark:[color-scheme:dark]',
                className,
            )}
            {...props}
        />
    );
}

export { DateTimeInput };
