// resources/js/pages/Recipes/Index.vue
<script setup lang="ts">
import { destroy, show, store } from '@/actions/App/Http/Controllers/RecipeController';
import InputError from '@/components/InputError.vue';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Skeleton } from '@/components/ui/skeleton';
import AppLayout from '@/layouts/AppLayout.vue';
import { type BreadcrumbItem, type PaginatedResource, type Recipe } from '@/types';
import { Form, Head, Link, router, WhenVisible } from '@inertiajs/vue3';
import { ChefHat, Clock, ExternalLink, Plus, Star, Trash2 } from 'lucide-vue-next';
import { ref } from 'vue';

interface Props {
    recipes: PaginatedResource<Recipe> | null;
    filters: Record<string, string>;
}

const props = defineProps<Props>();

const breadcrumbs: BreadcrumbItem[] = [{ title: 'Recipes', href: '/recipes' }];
const createOpen = ref(false);

function deleteRecipe(recipe: Recipe) {
    if (!confirm('Delete this recipe?')) return;
    router.delete(destroy(recipe.id).url);
}
</script>

<template>
    <Head title="Recipes" />

    <AppLayout :breadcrumbs="breadcrumbs">
        <div class="flex flex-col gap-4 p-6">
            <div class="flex items-center justify-between">
                <h1 class="text-xl font-semibold">Recipes</h1>

                <Dialog v-model:open="createOpen">
                    <DialogTrigger as-child>
                        <Button size="sm"><Plus class="mr-1 size-4" /> New Recipe</Button>
                    </DialogTrigger>
                    <DialogContent class="max-h-[90vh] overflow-y-auto">
                        <DialogHeader><DialogTitle>Create Recipe</DialogTitle></DialogHeader>
                        <Form :action="store()" method="post" enctype="multipart/form-data" class="space-y-4" v-slot="{ errors, processing }" reset-on-success>
                            <div class="grid gap-2">
                                <Label for="title">Title</Label>
                                <Input id="title" name="title" placeholder="Recipe name" required />
                                <InputError :message="errors.title" />
                            </div>
                            <div class="grid gap-2">
                                <Label for="description">Description</Label>
                                <Input id="description" name="description" placeholder="Brief description" />
                            </div>
                            <div class="grid grid-cols-2 gap-3">
                                <div class="grid gap-2">
                                    <Label for="category">Category</Label>
                                    <select id="category" name="category" class="h-9 w-full rounded-md border bg-background px-3 text-sm">
                                        <option value="">None</option>
                                        <option value="breakfast">Breakfast</option>
                                        <option value="lunch">Lunch</option>
                                        <option value="dinner">Dinner</option>
                                        <option value="snack">Snack</option>
                                        <option value="dessert">Dessert</option>
                                        <option value="drink">Drink</option>
                                    </select>
                                </div>
                                <div class="grid gap-2">
                                    <Label for="servings">Servings</Label>
                                    <Input id="servings" name="servings" type="number" min="1" placeholder="4" />
                                </div>
                            </div>
                            <div class="grid grid-cols-2 gap-3">
                                <div class="grid gap-2">
                                    <Label for="prep_time_minutes">Prep (min)</Label>
                                    <Input id="prep_time_minutes" name="prep_time_minutes" type="number" min="0" placeholder="15" />
                                </div>
                                <div class="grid gap-2">
                                    <Label for="cook_time_minutes">Cook (min)</Label>
                                    <Input id="cook_time_minutes" name="cook_time_minutes" type="number" min="0" placeholder="30" />
                                </div>
                            </div>
                            <div class="grid gap-2">
                                <Label for="instructions">Instructions</Label>
                                <textarea id="instructions" name="instructions" rows="4" required placeholder="Step by step instructions…"
                                    class="w-full rounded-md border bg-background px-3 py-2 text-sm placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-ring" />
                                <InputError :message="errors.instructions" />
                            </div>
                            <div class="grid gap-2">
                                <Label for="photo">Photo</Label>
                                <Input id="photo" name="photo" type="file" accept="image/*" />
                                <InputError :message="errors.photo" />
                            </div>
                            <Button type="submit" class="w-full" :disabled="processing">
                                {{ processing ? 'Creating…' : 'Create Recipe' }}
                            </Button>
                        </Form>
                    </DialogContent>
                </Dialog>
            </div>

            <WhenVisible :data="['recipes']" key="recipes-list">
                <template #fallback>
                    <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                        <Skeleton v-for="i in 6" :key="i" class="h-40 rounded-xl" />
                    </div>
                </template>

                <div v-if="recipes && recipes.data.length === 0" class="rounded-xl border border-dashed py-16 text-center text-sm text-muted-foreground">
                    No recipes yet. Add your first one!
                </div>

                <div v-else-if="recipes" class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                    <div v-for="recipe in recipes.data" :key="recipe.id"
                        class="group relative flex flex-col overflow-hidden rounded-xl border transition hover:shadow-md">
                        <div v-if="recipe.photo_path" class="aspect-video w-full overflow-hidden">
                            <img :src="`/storage/${recipe.photo_path}`" :alt="recipe.title" class="h-full w-full object-cover" />
                        </div>
                        <div v-else class="flex aspect-video items-center justify-center bg-muted">
                            <ChefHat class="size-8 text-muted-foreground" />
                        </div>

                        <div class="flex flex-1 flex-col p-4">
                            <p class="font-semibold">{{ recipe.title }}</p>
                            <p v-if="recipe.description" class="mt-1 line-clamp-2 text-xs text-muted-foreground">{{ recipe.description }}</p>

                            <div class="mt-auto flex items-center justify-between pt-3 text-xs text-muted-foreground">
                                <span v-if="recipe.total_time_minutes > 0" class="flex items-center gap-1">
                                    <Clock class="size-3" /> {{ recipe.total_time_minutes }}m
                                </span>
                                <span v-if="recipe.rating" class="flex items-center gap-1">
                                    <Star class="size-3 fill-yellow-400 text-yellow-400" /> {{ recipe.rating }}/5
                                </span>
                            </div>

                            <div class="mt-3 flex items-center justify-between">
                                <Link :href="show(recipe.id).url" class="text-sm font-medium hover:underline">
                                    View <ExternalLink class="ml-1 inline size-3" />
                                </Link>
                                <Button variant="ghost" size="icon" @click="deleteRecipe(recipe)">
                                    <Trash2 class="size-4 text-destructive" />
                                </Button>
                            </div>
                        </div>
                    </div>
                </div>
            </WhenVisible>
        </div>
    </AppLayout>
</template>

// resources/js/pages/Recipes/Index.tsx
import { destroy, show, store } from '@/actions/App/Http/Controllers/RecipeController';
import InputError from '@/components/InputError';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Skeleton } from '@/components/ui/skeleton';
import AppLayout from '@/layouts/AppLayout';
import type { BreadcrumbItem, PaginatedResource, Recipe } from '@/types';
import { Head, Link, router, useForm } from '@inertiajs/react';
import { ChefHat, Clock, ExternalLink, Plus, Star, Trash2 } from 'lucide-react';
import { useState } from 'react';

interface Props {
    recipes: PaginatedResource<Recipe> | null;
    filters: Record<string, string>;
}

const breadcrumbs: BreadcrumbItem[] = [{ title: 'Recipes', href: '/recipes' }];

export default function RecipesIndex({ recipes }: Props) {
    const [createOpen, setCreateOpen] = useState(false);
    const { data, setData, post, processing, errors, reset } = useForm({
        title: '',
        description: '',
        category: '',
        servings: '',
        prep_time_minutes: '',
        cook_time_minutes: '',
        instructions: '',
        photo: null as File | null,
    });

    function handleCreate(e: React.FormEvent) {
        e.preventDefault();
        post(store().url, {
            forceFormData: true,
            onSuccess: () => {
                setCreateOpen(false);
                reset();
            },
        });
    }

    function deleteRecipe(recipe: Recipe) {
        if (!confirm('Delete this recipe?')) {
            return;
        }

        router.delete(destroy(recipe.id).url);
    }

    return (
        <>
            <Head title="Recipes" />
            <AppLayout breadcrumbs={breadcrumbs}>
                <div className="flex flex-col gap-4 p-6">
                    <div className="flex items-center justify-between">
                        <h1 className="text-xl font-semibold">Recipes</h1>
                        <Dialog open={createOpen} onOpenChange={setCreateOpen}>
                            <DialogTrigger asChild>
                                <Button size="sm">
                                    <Plus className="mr-1 size-4" /> New Recipe
                                </Button>
                            </DialogTrigger>
                            <DialogContent className="max-h-[90vh] overflow-y-auto">
                                <DialogHeader>
                                    <DialogTitle>Create Recipe</DialogTitle>
                                </DialogHeader>
                                <form onSubmit={handleCreate} className="space-y-4">
                                    <div className="grid gap-2">
                                        <Label>Title</Label>
                                        <Input
                                            value={data.title}
                                            onChange={(e) => setData('title', e.target.value)}
                                            placeholder="Recipe name"
                                            required
                                        />
                                        <InputError message={errors.title} />
                                    </div>
                                    <div className="grid gap-2">
                                        <Label>Description</Label>
                                        <Input
                                            value={data.description}
                                            onChange={(e) => setData('description', e.target.value)}
                                            placeholder="Brief description"
                                        />
                                    </div>
                                    <div className="grid grid-cols-2 gap-3">
                                        <div className="grid gap-2">
                                            <Label>Category</Label>
                                            <select
                                                value={data.category}
                                                onChange={(e) => setData('category', e.target.value)}
                                                className="h-9 w-full rounded-md border bg-background px-3 text-sm"
                                            >
                                                <option value="">None</option>
                                                <option value="breakfast">Breakfast</option>
                                                <option value="lunch">Lunch</option>
                                                <option value="dinner">Dinner</option>
                                                <option value="snack">Snack</option>
                                                <option value="dessert">Dessert</option>
                                                <option value="drink">Drink</option>
                                            </select>
                                        </div>
                                        <div className="grid gap-2">
                                            <Label>Servings</Label>
                                            <Input
                                                type="number"
                                                min="1"
                                                value={data.servings}
                                                onChange={(e) => setData('servings', e.target.value)}
                                                placeholder="4"
                                            />
                                        </div>
                                    </div>
                                    <div className="grid grid-cols-2 gap-3">
                                        <div className="grid gap-2">
                                            <Label>Prep (min)</Label>
                                            <Input
                                                type="number"
                                                min="0"
                                                value={data.prep_time_minutes}
                                                onChange={(e) => setData('prep_time_minutes', e.target.value)}
                                                placeholder="15"
                                            />
                                        </div>
                                        <div className="grid gap-2">
                                            <Label>Cook (min)</Label>
                                            <Input
                                                type="number"
                                                min="0"
                                                value={data.cook_time_minutes}
                                                onChange={(e) => setData('cook_time_minutes', e.target.value)}
                                                placeholder="30"
                                            />
                                        </div>
                                    </div>
                                    <div className="grid gap-2">
                                        <Label>Instructions</Label>
                                        <textarea
                                            value={data.instructions}
                                            onChange={(e) => setData('instructions', e.target.value)}
                                            rows={4}
                                            required
                                            placeholder="Step by step instructions…"
                                            className="w-full rounded-md border bg-background px-3 py-2 text-sm placeholder:text-muted-foreground focus:ring-1 focus:ring-ring focus:outline-none"
                                        />
                                        <InputError message={errors.instructions} />
                                    </div>
                                    <div className="grid gap-2">
                                        <Label>Photo</Label>
                                        <Input type="file" accept="image/*" onChange={(e) => setData('photo', e.target.files?.[0] ?? null)} />
                                        <InputError message={errors.photo} />
                                    </div>
                                    <Button type="submit" className="w-full" disabled={processing}>
                                        {processing ? 'Creating…' : 'Create Recipe'}
                                    </Button>
                                </form>
                            </DialogContent>
                        </Dialog>
                    </div>

                    {!recipes ? (
                        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                            {[...Array(6)].map((_, i) => (
                                <Skeleton key={i} className="h-40 rounded-xl" />
                            ))}
                        </div>
                    ) : recipes.data.length === 0 ? (
                        <div className="rounded-xl border border-dashed py-16 text-center text-sm text-muted-foreground">
                            No recipes yet. Add your first one!
                        </div>
                    ) : (
                        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                            {recipes.data.map((recipe) => (
                                <div
                                    key={recipe.id}
                                    className="group relative flex flex-col overflow-hidden rounded-xl border transition hover:shadow-md"
                                >
                                    {recipe.photo_path ? (
                                        <div className="aspect-video w-full overflow-hidden">
                                            <img src={`/storage/${recipe.photo_path}`} alt={recipe.title} className="h-full w-full object-cover" />
                                        </div>
                                    ) : (
                                        <div className="flex aspect-video items-center justify-center bg-muted">
                                            <ChefHat className="size-8 text-muted-foreground" />
                                        </div>
                                    )}
                                    <div className="flex flex-1 flex-col p-4">
                                        <p className="font-semibold">{recipe.title}</p>
                                        {recipe.description && (
                                            <p className="mt-1 line-clamp-2 text-xs text-muted-foreground">{recipe.description}</p>
                                        )}
                                        <div className="mt-auto flex items-center justify-between pt-3 text-xs text-muted-foreground">
                                            {recipe.total_time_minutes > 0 && (
                                                <span className="flex items-center gap-1">
                                                    <Clock className="size-3" /> {recipe.total_time_minutes}m
                                                </span>
                                            )}
                                            {recipe.rating && (
                                                <span className="flex items-center gap-1">
                                                    <Star className="size-3 fill-yellow-400 text-yellow-400" /> {recipe.rating}/5
                                                </span>
                                            )}
                                        </div>
                                        <div className="mt-3 flex items-center justify-between">
                                            <Link href={show(recipe.id).url} className="text-sm font-medium hover:underline">
                                                View <ExternalLink className="ml-1 inline size-3" />
                                            </Link>
                                            <Button variant="ghost" size="icon" onClick={() => deleteRecipe(recipe)}>
                                                <Trash2 className="size-4 text-destructive" />
                                            </Button>
                                        </div>
                                    </div>
                                </div>
                            ))}
                        </div>
                    )}
                </div>
            </AppLayout>
        </>
    );
}
